
export const GET_NEWS_FEED_ATTEMPING = 'GET_NEWS_FEED_ATTEMPING';
export const GET_NEWS_FEED_FAILED = 'GET_NEWS_FEED_FAILED';
export const GET_NEWS_FEED_SUCCESS = 'GET_NEWS_FEED_SUCCESS';


export const CHANGE_THEME_ATTEMPING = 'CHANGE_THEME_ATTEMPING';
export const CHANGE_THEME_SUCCESS = 'CHANGE_THEME_SUCCESS';


export const CHANGE_LANGUAGE_ATTEMPING = 'CHANGE_LANGUAGE_ATTEMPING';
export const CHANGE_LANGUAGE_SUCCESS = 'CHANGE_LANGUAGE_SUCCESS';
